
/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(kurtosis.h)                                                */
/* BINDTOOL_HEADER_FILE_HASH(be036eea1605a157d97b6c907ba6a457)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/kurtosis.h>
// pydoc.h is automatically generated in the build directory
#include <kurtosis_pydoc.h>

void bind_kurtosis(py::module& m)
{
    using kurtosis = ::gr::satellites::kurtosis;

    py::class_<kurtosis,
               gr::sync_decimator,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<kurtosis>>(m, "kurtosis", D(kurtosis))
        .def(py::init(&kurtosis::make),
             py::arg("block_size"),
             py::arg("vlen") = 1,
             D(kurtosis, make));
}
