
/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(level_to_message.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(be690657f1ef6d1eac76750c772260cb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/level_to_message.h>
// pydoc.h is automatically generated in the build directory
#include <level_to_message_pydoc.h>

void bind_level_to_message(py::module& m)
{
    using level_to_message = ::gr::satellites::level_to_message;

    py::class_<level_to_message,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<level_to_message>>(
        m, "level_to_message", D(level_to_message))
        .def(py::init(&level_to_message::make),
             py::arg("threshold"),
             D(level_to_message, make));
}
