/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(lilacsat1_demux.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0c0dfcb2ca665db072bf659bc6b08d45)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/lilacsat1_demux.h>
// pydoc.h is automatically generated in the build directory
#include <lilacsat1_demux_pydoc.h>

void bind_lilacsat1_demux(py::module& m)
{

    using lilacsat1_demux    = ::gr::satellites::lilacsat1_demux;


    py::class_<lilacsat1_demux, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<lilacsat1_demux>>(m, "lilacsat1_demux", D(lilacsat1_demux))

        .def(py::init(&lilacsat1_demux::make),
           py::arg("tag"),
           D(lilacsat1_demux,make)
        )
        



        ;




}








