/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(message_counter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0b4ab766a4e12b8cb424f2447bd459ae)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/message_counter.h>
// pydoc.h is automatically generated in the build directory
#include <message_counter_pydoc.h>

void bind_message_counter(py::module& m)
{

    using message_counter = ::gr::satellites::message_counter;


    py::class_<message_counter,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<message_counter>>(m, "message_counter", D(message_counter))

        .def(py::init(&message_counter::make), D(message_counter, make))


        ;
}
