/*
 * Copyright 2025 Daniel Estevez <daniel@destevez.net>.
 *
 * This file is part of gr-satellites
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nanocom_golay_decode_length.h)                             */
/* BINDTOOL_HEADER_FILE_HASH(44cd41aca669cb8bd425cda0aa0fc7af)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/nanocom_golay_decode_length.h>
// pydoc.h is automatically generated in the build directory
#include <nanocom_golay_decode_length_pydoc.h>

void bind_nanocom_golay_decode_length(py::module& m)
{
    using nanocom_golay_decode_length = ::gr::satellites::nanocom_golay_decode_length;

    py::class_<nanocom_golay_decode_length,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<nanocom_golay_decode_length>>(
        m, "nanocom_golay_decode_length", D(nanocom_golay_decode_length))
        .def(py::init(&nanocom_golay_decode_length::make),
             py::arg("golay_start_tag_key"),
             py::arg("length_tag_key"),
             D(nanocom_golay_decode_length, make));
}
