/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_length_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(769ba1190b6ecee9caf4743126ebc68b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/pdu_length_filter.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_length_filter_pydoc.h>

void bind_pdu_length_filter(py::module& m)
{

    using pdu_length_filter    = ::gr::satellites::pdu_length_filter;


    py::class_<pdu_length_filter, gr::block, gr::basic_block,
        std::shared_ptr<pdu_length_filter>>(m, "pdu_length_filter", D(pdu_length_filter))

        .def(py::init(&pdu_length_filter::make),
           py::arg("min"),
           py::arg("max"),
           D(pdu_length_filter,make)
        )
        



        ;




}








