/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(u482c_encode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4a969f775f5affdc2d40c3d3418399fa)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/u482c_encode.h>
// pydoc.h is automatically generated in the build directory
#include <u482c_encode_pydoc.h>

void bind_u482c_encode(py::module& m)
{

    using u482c_encode = ::gr::satellites::u482c_encode;


    py::class_<u482c_encode, gr::block, gr::basic_block, std::shared_ptr<u482c_encode>>(
        m, "u482c_encode", D(u482c_encode))

        .def(py::init(&u482c_encode::make),
             py::arg("convolutional"),
             py::arg("scrambler"),
             py::arg("rs"),
             py::arg("preamble_len"),
             py::arg("flags_in_golay"),
             D(u482c_encode, make))


        ;
}
