#!/usr/bin/env python3

import satellites.core
from gnuradio import gr, blocks

import signal
import argparse
import sys

def argument_parser():
    description = 'gr-satellites - GNU Radio decoders for Amateur satellites'
    info = 'The satellite parameter can be specified using name, NORAD ID or path to YAML file'
    p = argparse.ArgumentParser(description = description, conflict_handler = 'resolve', prog = f'gr_satellites satellite', epilog = info)
    p_input = p.add_argument_group('input')
    p_input.add_argument('--wavfile', help = 'WAV input file')
    p_input.add_argument('--samp_rate', type = float, help = 'Sample rate (Hz)', required = True)
    p_input.add_argument('--udp', action = 'store_true', help = 'Use UDP input')
    p_input.add_argument('--udp_ip', default = '::', help = 'UDP input listen IP [default=%(default)r]')
    p_input.add_argument('--udp_port', default = '7355', type = int, help = 'UDP input listen port [default=%(default)r]')
    p_output = p.add_argument_group('output')
    p_output.add_argument('--kiss_out', help = 'KISS output file')
    p_output.add_argument('--kiss_append', action = 'store_true', help = 'Append to KISS output file')
    return p

def check_options(options, parser):
    if sum([bool(x) for x in [options.wavfile, options.udp]]) != 1:
        print('Need to specify exactly one of the following input sources: {--wavfile, --udp}', file = sys.stderr)
        parser.print_usage(file = sys.stderr)
        sys.exit(1)

def parse_satellite(satellite):
    if satellite.lower().endswith('.yml'):
        return {'file' : satellite}
    elif satellite.isnumeric():
        return {'norad' : int(satellite)}
    else:
        return {'name' : satellite}
    
class gr_satellites_top_block(gr.top_block):
    def __init__(self, parser):
        gr.top_block.__init__(self, 'gr-satellites top block')
        sat = parse_satellite(sys.argv[1])
        satellites.core.gr_satellites_flowgraph.add_options(parser, **sat)
        options = parser.parse_args(sys.argv[2:])
        check_options(options, parser)
        
        self.options = options
        
        self.flowgraph = satellites.core.gr_satellites_flowgraph(samp_rate = options.samp_rate, options = options, **sat)
        self.setup_input()
        self.connect(self.input, self.flowgraph)

    def setup_input(self):
        if self.options.wavfile is not None:
            return self.setup_wavfile_input()
        elif self.options.udp is True:
            return self.setup_udp_input()
        else:
            raise Exception('No input source set for flowgraph')

    def setup_wavfile_input(self):
        self.input = blocks.wavfile_source(self.options.wavfile, False)

    def setup_udp_input(self):
        self.udp = blocks.udp_source(gr.sizeof_short, self.options.udp_ip, self.options.udp_port, 1472, False)
        self.input = blocks.short_to_float(1, 32767)
        self.connect(self.udp, self.input)

def main():
    parser = argument_parser()
    if len(sys.argv) <= 1 or sys.argv[1][0] == '-':
        parser.print_usage(file = sys.stderr)
        sys.exit(1)
    
    tb = gr_satellites_top_block(parser)

    def sig_handler(sig=None, frame=None):
        tb.stop()
        tb.wait()
        sys.exit(0)

    signal.signal(signal.SIGINT, sig_handler)
    signal.signal(signal.SIGTERM, sig_handler)

    tb.start()
    tb.wait()
        
if __name__ == '__main__':
    main()
