.TH JY1SAT-SSDV 1 2020-09-28 gr-satellites "User commands"
.SH NAME
jy1sat_ssdv \- extracts SSDV images from a KISS file containing frames of the
JY1SAT satellite
.SH SYNOPSIS
.B jy1sat_ssdv
.IR jy1sat_frames.kss
.IR output_path
.SH DESCRIPTION
.PP
.B jy1sat_ssdv
forms part of gr-satellites and can be used to extract and
decoded SSDV images from a KISS file containing frames from JY1SAT.
.PP
gr-satellites is a GNU Radio out-of-tree module encompassing a collection of
telemetry decoders that supports many different Amateur satellites. It supports
most popular protocols, such as AX.25, the GOMspace NanoCom U482C and AX100
modems, an important part of the CCSDS stack, the AO-40 protocol used in the
FUNcube satellites, and several ad-hoc protocols used in other satellites.
.SH "SEE ALSO"
.BR gr_satellites (1)
