.TH SMOG-P-SPECTRUM 1 2020-09-28 gr-satellites "User commands"
.SH NAME
smog_p_spectrum \- plots spectrum data from SMOG-P/ATL-1
.SH SYNOPSIS
.B smog_p_spectrum
.IR spectrum_file
.SH DESCRIPTION
.PP
.B smog_p_spectrum
forms part of gr-satellites and can be used to plot the
spectrum data stored in a file received from SMOG-P or ATL-1.
.PP
gr-satellites is a GNU Radio out-of-tree module encompassing a collection of
telemetry decoders that supports many different Amateur satellites. It supports
most popular protocols, such as AX.25, the GOMspace NanoCom U482C and AX100
modems, an important part of the CCSDS stack, the AO-40 protocol used in the
FUNcube satellites, and several ad-hoc protocols used in other satellites.
.SH "SEE ALSO"
.BR gr_satellites (1)
